<?php
/**
 * @version		$Id$
 * @copyright	Copyright (C) 2005 - 2009 Open Source Matters. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 */

require_once JPATH_BASE.'/libraries/joomla/database/table/component.php';

/**
 * Test class for JTableComponent.
 * Generated by PHPUnit on 2009-10-08 at 22:05:53.
 */
class JTableComponentTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var    JTableComponent
	 * @access protected
	 */
	protected $object;
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp() {
		$this->object = new JTableComponent;
	}
	
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown() {
	}
	
	/**
	 * @todo Implement testLoadByOption().
	 */
	public function testLoadByOption() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
	
	/**
	 * @todo Implement testCheck().
	 */
	public function testCheck() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
	
	/**
	 * @todo Implement testBind().
	 */
	public function testBind() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
?>
