<div class="contentheading">{$maintitle}</div>

<img src="media/images/workgroups_documentation.jpg" alt="Documentation Workgroup Logo" title="Documentation Workgroup Logo" style="float: right" />
<br />
<p>These pages are automatically generated by the <a class="intro-link" href="{$phpdocwebsite}">phpDocumentor</a> package from an analysis of the Joomla! source code
and making use of specially formatted comments embedded in the source code itself.</p>

<p>The Joomla! Content Management System (CMS) is an application built on top of the Joomla! Framework.  This website documents the API of the Joomla! Framework and so does not include code from the Joomla! CMS.  In particular, the legacy API is now implemented in a plug-in which is part of the CMS and so is no longer documented here.</p>

<p>
This is what you will find here:</p>

<ul>
 <li>The Joomla! Framework API, called simply <a class="intro-link" href="li_Joomla-Framework.html">Joomla-Framework</a>.</li>
 <li>A number of third-party libraries used by Joomla! and/or available for use by third-party Joomla! extension developers.  Please note
that the Joomla! Developer Documentation Team is not responsible for maintaining documentation, including this automatically generated
documentation, for third-party libraries.</li>
</ul>
<p>You can select which package to view using the drop-down list in the menu on the left of this screen.</p>

<p>Third-party libraries are documented here for completeness and because they contain valuable information not available elsewhere.  However, to get the best out of the Joomla! Framework, please try to use the Joomla! API calls in preference to calling the libraries directly.</p>

<p>Additional documentation is available on the <a class="intro-link" href="http://dev.joomla.org">Joomla! Developer Network</a> website and in particular
there is a manually produced <a class="intro-link" href="http://dev.joomla.org/component/option,com_jd-wiki/Itemid,32/">API reference wiki</a> which has
additional information and example code for classes and methods in the Joomla! Framework.</p>

<p>This website covers the latest official release of the Joomla! Framework.  The equivalent to this site for the <a href="svn/">latest SVN code</a> is available in the svn subdirectory.</p>
<br />
{config_load file=release.ini}
<div class="release-box">These pages were generated from {#package#} {#release#}<br />({#date#})</div>

<table>
  <tr><th align="center">Symbol</th><th>Description</th>
      <th align="center">Symbol</th><th>Description</th>
      <th align="center">Symbol</th><th>Description</th></tr>

  <tr><td align="center"><img src="media/images/Class.png" alt="Class" title="Class" /></td>
      <td>Class</td>
      <td align="center"><img src="media/images/Method.png" alt="Method" title="Method" /></td>
      <td>Method</td>
      <td align="center"><img src="media/images/Variable.png" alt="Variable" title="Variable" /></td>
      <td>Variable</td></tr>

  <tr><td align="center"><img src="media/images/PrivateClass.png" alt="Private class" title="Private class" /></td>
      <td>Private class</td>
      <td align="center"><img src="media/images/PrivateMethod.png" alt="Private method" title="Private method" /></td>
      <td>Private method</td>
      <td align="center"><img src="media/images/PrivateVariable.png" alt="Private variable" title="Private variable" /></td>
      <td>Private variable</td></tr>

  <tr><td align="center"><img src="media/images/AbstractClass.png" alt="Abstract class" title="Abstract class" /></td>
      <td>Abstract class</td>
      <td align="center"><img src="media/images/AbstractMethod.png" alt="Abstract method" title="Abstract method" /></td>
      <td>Abstract method</td>
      <td align="center"><img src="media/images/StaticVariable.png" alt="Static variable" title="Static variable" /></td>
      <td>Static variable</td></tr>

  <tr><td align="center"><img src="media/images/AbstractPrivateClass.png" alt="Abstract private class" title="Abstract private class" /></td>
      <td>Abstract private class</td>
      <td></td>
      <td></td>
      <td align="center"><img src="media/images/Global.png" alt="Global" title="Global" /></td>
      <td>Global</td></tr>

  <tr><td></td><td></td>
      <td align="center"><img src="media/images/StaticMethod.png" alt="Static method" title="Static method" /></td>
      <td>Static method</td>
      <td align="center"><img src="media/images/Constant.png" alt="Constant" title="Constant" /></td>
      <td>Constant</td></tr>
      
  <tr><td align="center"><img src="media/images/folder.png" alt="File folder" title="File folder" /></td>
      <td>File folder</td>
      <td align="center"><img src="media/images/Constructor.png" alt="Constructor" title="Constructor" /></td>
      <td>Constructor</td>
      <td></td><td></td></tr>

  <tr><td align="center"><img src="media/images/class_folder.png" alt="Class folder" title="Class folder" /></td>
      <td>Class folder</td>
      <td align="center"><img src="media/images/Destructor.png" alt="Destructor" title="Destructor" /></td>
      <td>Destructor</td>
      <td align="center"><img src="media/images/Page.png" alt="File" title="File" /></td>
      <td>File</td></tr>

  <tr><td align="center"><img src="media/images/function_folder.png" alt="Function folder" title="Function folder" /></td>
      <td>Function folder</td>
      <td align="center"><img src="media/images/Function.png" alt="Function" title="Function" /></td>
      <td>Function</td>
      <td align="center"><img src="media/images/Index.png" alt="Index" title="Index" /></td>
      <td>Index</td></tr>

  <tr><td align="center"><img src="media/images/tutorial_folder.png" alt="Tutorial folder" title="Tutorial folder" /></td>
      <td>Tutorial folder</td>
      <td></td>
      <td></td>
      <td align="center"><img src="media/images/tutorial.png" alt="Tutorial" title="Tutorial" /></td>
      <td>Tutorial</td></tr>

  <tr><td align="center"><img src="media/images/package_folder.png" alt="Package folder" title="Package folder" /></td>
      <td>Package folder</td>
      <td></td>
      <td></td>
      <td align="center"><img src="media/images/package.png" alt="Subpackage" title="Subpackage" /></td>
      <td>Subpackage</td></tr>

</table>
<br />

<p>If you notice any errors on any of these pages then please take a moment to report the problem on the <a class="intro-link" href="http://forum.joomla.org/index.php/board,60.0.html">Developer Documentation Forum</a>.</p>

