<?php
require_once 'PHPUnit/Framework.php';

include_once JPATH_BASE.'/libraries/joomla/html/html.php';
require_once JPATH_BASE.'/libraries/joomla/html/html/behavior.php';

/**
 * Test class for JHtmlBehavior.
 * Generated by PHPUnit on 2009-10-27 at 15:39:41.
 */
class JHtmlBehaviorTest extends JoomlaTestCase
{
	/**
	 * @var JHtmlBehavior
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->saveFactoryState();
//		$this->object = new JHtmlBehavior;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->restoreFactoryState();

		// reregister the script method
		JHtml::unregister('script');
	}

	/**
	 * @todo Implement testFramework().
	 */
	public function testFramework()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMootools().
	 */
	public function testMootools()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCaption().
	 */
	public function testCaption()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFormvalidation().
	 */
	public function testFormvalidation()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSwitcher().
	 */
	public function testSwitcher()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCombobox().
	 */
	public function testCombobox()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testTooltip().
	 */
	public function testTooltip()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testModal().
	 */
	public function testModal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	protected $uploaderScriptCalls = array(
		array('system/swf.js', false, true),
		array('system/progressbar.js', false, true),
		array('system/uploader.js', false, true)
	);


	public function uploaderScriptMock($file, $framework, $relative)
	{
		foreach($this->uploaderScriptCalls AS $k => $v) {
			if ($file == $v[0] && $framework == $v[1] && $relative == $v[2])
			{
				unset($this->uploaderScriptCalls[$k]);
				return;
			}
		}
		$this->uploaderScriptCalls[] = array(false, false, false);
		return;
	}

	public function addScriptDeclaration($string = null) {
		static $script;

		if($string) {
			$script = $string;
		}

		return $script;
	}


	/**
	 * Tests various thing about uploader
	 * 
	 */
	public function testUploader()
	{
		// we register our mock for the script method
		JHtml::register('script', array($this, 'uploaderScriptMock'));

		JFactory::$document = $this;

		JHtml::_('behavior.uploader', 'uploader_id', array());

		$addedScript = $this->addScriptDeclaration();
		
		$this->assertThat(
			preg_match('var Uploader = new FancyUpload2', $addedScript),
			$this->equalTo(1)
		);

	}

	/**
	 * @todo Implement testTree().
	 */
	public function testTree()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalendar().
	 */
	public function testCalendar()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testKeepalive().
	 */
	public function testKeepalive()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}
}
