<?php
/**
 * Test class for JArrayHelper.
 * Generated by PHPUnit_Util_Skeleton on 2007-02-22 at 04:17:52.
 *
 * @package Joomla
 * @subpackage UnitTest
 * @version $Id$
 */

// Call TestOfJArrayHelper::main() if this source file is executed directly.
if (!defined('JUNIT_MAIN_METHOD')) {
	define('JUNIT_MAIN_METHOD', 'TestOfJArrayHelper::main');
	$JUNIT_ROOT = substr(__FILE__, 0, strpos(__FILE__, DIRECTORY_SEPARATOR.'unittest'));
	require_once($JUNIT_ROOT.'/unittest/setup.php');
}

require_once('libraries/joomla/utilities/array.php');

class TestOfJArrayHelper extends UnitTestCase {

	/**
	 * Runs the test methods of this class.
	 *
	 * @access public
	 * @static
	 */
	function main() {
		$self = new TestOfJArrayHelper;
		$self->run(UnitTestHelper::getReporter());
	}

	/**
	 * Sets up the fixture, for example, open a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	function setUp() {
	}

	/**
	 * Tears down the fixture, for example, close a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	function tearDown() {
	}

	/**
	 * @todo Implement testToInteger().
	 */
	function testToInteger()
	{
		$array   = array("1","2","3");
		$compare = array(1 , 2 , 3);
		JArrayHelper::toInteger($array);
		$this->assertEqual($array, $compare);
	}

	function testToInteger_default()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();
	}

	/**
	 * @todo Implement testToObject().
	 */
	function testToObject()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();
	}

	/**
	 * @todo Implement testFromObject().
	 */
	function testFromObject()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();
	}

	/**
	 * @todo Implement testGetColumn().
	 */
	function testGetColumn()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();
	}

	/**
	 * @todo Implement testGetValue().
	 */
	function testGetValue()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();
	}

	/**
	 * @todo Implement testSortObjects().
	 */
	function testSortObjects()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();
	}

	/**
	 * @todo Implement test_sortObjects().
	 */
	function test_sortObjects()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();
	}

}

// Call TestOfJArrayHelper::main() if this source file is executed directly.
if (JUNIT_MAIN_METHOD == "TestOfJArrayHelper::main") {
	TestOfJArrayHelper::main();
}
