/**
 * @version		$Id$
 * @copyright	Copyright (C) 2005 - 2009 Open Source Matters. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 */

require_once JPATH_BASE.'/libraries/joomla/filesystem/support/stringcontroller.php';
/**
 * Test class for JStringController.
 * Generated by PHPUnit on 2009-11-08 at 18:35:30.
 */
class JStringControllerTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var JStringController
	 */
	protected $object;
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new JStringController;
	}
	
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}
	
	/**
	 * @todo Implement test_getArray().
	 */
	public function test_getArray() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
	
	/**
	 * @todo Implement testCreateRef().
	 */
	public function testCreateRef() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
	
	/**
	 * @todo Implement testGetRef().
	 */
	public function testGetRef() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
?>
