<?php
require_once 'PHPUnit/Framework.php';
require_once 'categories.php';
/**
 * Test class for JCategories.
 * Generated by PHPUnit on 2009-10-08 at 11:55:02.
 */
class JCategoriesTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var    JCategories
	 * @access protected
	 */
	protected $object;
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp() {
		$this->object = new JCategories;
	}
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown() {
	}
	/**
	 * @todo Implement testGetInstance().
	 */
	public function testGetInstance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
	/**
	 * @todo Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
?>
