<?php
require_once 'PHPUnit/Framework.php';
require_once JPATH_BASE . '/libraries/joomla/user/authentication.php';

/**
 * Test class for JAuthentication.
 * Generated by PHPUnit on 2009-10-26 at 22:45:21.
 */
class JAuthenticationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JAuthentication
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new JAuthentication;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Testing GetInstance().
     *
     * @return void
     */
    public function testGetInstance()
    {
    	$instance1 = JAuthentication::getInstance();
    	$this->assertThat(
    		JError::getError(),
    		$this->equalTo(null)
    	);

    	$instance2 = JAuthentication::getInstance();
    	$this->assertThat(
    		JError::getError(),
    		$this->equalTo(null)
    	);

		$this->assertThat(
			$instance1,
			$this->equalTo($instance2)
		);
    }

    /**
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
