<?php
/**
 * Custom rule for the JAPI DokuWiki plugin
 * {#JAPI Joomla.Framework Package Classname::method ReviewDate DocStatusCode #}

 * @category   Text
 * @package    Text_Wiki
 * @author     Rene Serradeil <serradeil@webmechanic.bizt>
 */

/**
 *
 * @category   Text
 * @package    Text_Wiki
 * @author     Rene Serradeil <serradeil@webmechanic.bizt>
 */
class Text_Wiki_Parse_Japi extends Text_Wiki_Parse
{
    /**
    * Configuration options for this parser rule.
    * @access public
    * @var string
    */
    var $conf = array();

    /**
    * Regular expression to find matching text for this rule.
    * @access public
    * @var string
    * @see parse()
    */
    var $regex = '/({#JAPI\s+([\w\s-_:\.]+)#\})/ism';

    /**
    * Abstract method to generate replacements for matched text.
    *
    * @access public
    * @param array $matches An array of matches from the parse() method
    * as generated by preg_replace_callback.  $matches[0] is the full
    * matched string, $matches[1] is the first matched pattern,
    * $matches[2] is the second matched pattern, and so on.
    * @return string The processed text replacement; defaults to the
    * full matched string (i.e., no changes to the text).
    * @see Text_Wiki_Parse::parse()
    */

    function process(&$matches)
    {
		$items = explode(' ', $matches[2]);
    	$options = array(
    		'text' => $matches[2],
    		'items'=> array(
	    		'home'  => $items[0],
    			'pack'  => $items[1],
    			'class' => $items[2],
    			'meth'  => '',
    			)
    	);
    	return $this->wiki->addToken($this->rule, $options);
    }

}
?>
