<?php
/* *Id$ */
/**
 * Test class for JObserver.
 * Generated by PHPUnit on 2009-10-08 at 11:46:14.
 */
class JObserverTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var    JObserver
	 * @access protected
	 */
	protected $object;
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp() {
		$this->object = new JObserver;
	}
	
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown() {
	}
}
?>
