<?php
/**
 * Test class for JRoute.
 * Generated by PHPUnit_Util_Skeleton on 2007-02-27 at 05:36:09.
 *
 * @package 	Joomla
 * @subpackage 	UnitTest
 * @version 	$Id$
 */

// Call TestOfJRoute::main() if this source file is executed directly.
if (!defined('JUNITTEST_MAIN_METHOD')) {
    define('JUNITTEST_MAIN_METHOD', 'TestOfJRoute::main');
    $JUNITTEST_ROOT = substr(__FILE__, 0, strpos(__FILE__, DIRECTORY_SEPARATOR.'unittest'));
	require_once($JUNITTEST_ROOT.'/unittest/prepend.php');
}

require_once('libraries/joomla/application/router.php');

class TestOfJRoute extends UnitTestCase {

	/**
	 * Runs the test methods of this class.
	 *
	 * @access public
	 * @static
	 */
	function main() {
		$self = new TestOfJRoute;
		$self->run( UnitTestHelper::getReporter() );
	}

	/**
	 * Sets up the fixture, for example, open a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	function setUp() {
	}

	/**
	 * Tears down the fixture, for example, close a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	function tearDown() {
	}

	/**
	 * Test Cases
	 */
	function test__construct()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();

		$instance = new JRoute;
		$this->assertIsA($instance, 'JRoute');

	}


	/**
	 * @todo Implement test_()
	 *
	 * Parameters: 2
	 *   required: 1
	 * @param #1  $url required , allows NULL
	 * @param #2  $ssl optional (0) , allows NULL
	 */
	function test_()
	{
		// Remove the following line when you implement this test.
		return $this->_reporter->setMissingTestCase();

		// replace with sth. useful :)
		$url = null;
		$ssl = 0;
		$compare1 = JRoute::_( $url, $ssl );
		$compare2 = JRoute::_( $url, $ssl );
	}


}

// Call TestOfJRoute::main() if this source file is executed directly.
if (JUNITTEST_MAIN_METHOD == 'TestOfJRoute::main') {
	TestOfJRoute::main();
}
