<?php
/**
 * @version		$Id$
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 */

require_once JPATH_BASE.'/libraries/joomla/application/component/helper.php';
require_once JPATH_BASE.'/tests/unit/JoomlaDatabaseTestCase.php';
/**
 * Test class for JComponentHelper.
 * Generated by PHPUnit on 2009-10-08 at 21:18:55.
 */
class JComponentHelperTest extends JoomlaDatabaseTestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
        parent::setUp();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
        parent::tearDown();
	}

	/**
	 * Gets the data set to be loaded into the database during setup
	 *
	 * @return xml dataset
	 */
	protected function getDataSet()
	{
		return $this->createXMLDataSet(JPATH_BASE . '/tests/unit/stubs/jos_extensions.xml');
	}

	/**
     * Test getting the component information
     *
	 * @todo Implement testGetComponent().
	 */
	public function testGetComponent()
	{
        $result = JComponentHelper::getComponent("com_banners");
        $this->assertThat(
            $result,
			$this->isInstanceOf('stdClass'),
            'is it stdClass'
		);
		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testIsEnabled().
	 */
	public function testIsEnabled()
	{
        $result = JComponentHelper::getComponent("com_weblinks");
        $this->assertThat(
            0,
			$this->equalTo($result->enabled),
            'is it enabled'
		);
		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetParams().
	 */
	public function testGetParams()
	{
        $result = JComponentHelper::getComponent("com_media");
        $this->assertThat(
            new JRegistry( array(
                "upload_extensions" => "bmp,csv,doc,gif,ico,jpg,jpeg,odg,odp,ods,odt,pdf,png,ppt,swf,txt,xcf,xls,BMP,CSV,DOC,GIF,ICO,JPG,JPEG,ODG,ODP,ODS,ODT,PDF,PNG,PPT,SWF,TXT,XCF,XLS",
                "upload_maxsize" => "10485760",
                "file_path" => "images",
                "image_path" => "images",
                "restrict_uploads" => 1,
                "allowed_media_usergroup" => 3,
                "check_mime" => 1,
                "image_extensions" => "bmp,gif,jpg,png",
                "ignore_extensions" => "",
                "upload_mime" => "image/jpeg,image/gif,image/png,image/bmp,application/x-shockwave-flash,application/msword,application/excel,application/pdf,application/powerpoint,text/plain,application/x-zip",
                "upload_mime_illegal" => "text/html",
                "enable_flash" => 0 )
            ),
			$this->equalTo($result->params),
            'Are the params right'
		);
		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testRenderComponent().
	 */
	public function testRenderComponent()
	{
        $result = JComponentHelper::renderComponent("com_login");
        $this->assertThat(
            null,
            $this->equalTo($result),
            "did it render"
        );
		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}