<?php
/**
 * @version		$Id$
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 */

require_once JPATH_BASE.'/libraries/joomla/application/component/view.php';
/**
 * Test class for JView.
 * Generated by PHPUnit on 2009-10-08 at 21:21:58.
 */
class JViewTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var JView
	 */
	protected $object;
	 
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		if (!defined('JPATH_COMPONENT')) {
			define('JPATH_COMPONENT', JPATH_BASE.'/components/com_foobar');
		}
		$_SERVER['REQUEST_METHOD'] = 'get';
		$_SERVER['HTTP_HOST'] = 'example.com';
		$app = JFactory::getApplication('site');
		$this->object = new JView;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @todo Implement testDisplay().
	 */
	public function testDisplay()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testAssign().
	 */
	public function testAssign()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testAssignRef().
	 */
	public function testAssignRef()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testEscape().
	 */
	public function testEscape()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetModel().
	 */
	public function testGetModel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * Test JView::getLayout
	 *
	 * @since	1.6
	 */
	public function testGetLayout()
	{
		$this->assertEquals($this->object->getLayout(),'default');
		$this->object->setLayout('layout1');
		$this->assertEquals($this->object->getLayout(),'layout1');
		$this->object->setLayout(array('system'=>'layout2'));
		$this->assertEquals($this->object->getLayout(),'layout1');
		JFactory::getApplication()->setTemplate('system');
		$this->assertEquals($this->object->getLayout(),'layout2');
	}

	/**
	 * @todo Implement testGetName().
	 */
	public function testGetName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testSetModel().
	 */
	public function testSetModel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * Test JView::setLayout
	 *
	 * @since	1.6
	 */
	public function testSetLayout()
	{
		$layout = 'layout1';
		$this->assertEquals($this->object->setLayout($layout),'default');
		$layout = array('_'=>'layout2');
		$this->assertEquals($this->object->setLayout($layout),'layout1');
		$layout = array('template1'=>'layout3');
		$this->assertEquals($this->object->setLayout($layout),array('_'=>'layout2'));
		$layout = array('_'=>'layout5', 'template2'=>'layout4');
		$this->assertEquals($this->object->setLayout($layout),array('_'=>'layout2', 'template1'=>'layout3'));
		$this->assertEquals($this->object->setLayout(null),array('_'=>'layout5', 'template1'=>'layout5','template2'=>'layout4'));
	}

	/**
	 * @todo Implement testSetLayoutExt().
	 */
	public function testSetLayoutExt()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testSetEscape().
	 */
	public function testSetEscape()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testAddTemplatePath().
	 */
	public function testAddTemplatePath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testAddHelperPath().
	 */
	public function testAddHelperPath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testLoadTemplate().
	 */
	public function testLoadTemplate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testLoadHelper().
	 */
	public function testLoadHelper()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_setPath().
	 */
	public function test_setPath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_addPath().
	 */
	public function test_addPath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_createFileName().
	 */
	public function test_createFileName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
