<?php
/**
 * Test class for JFrameworkConfig.
 *
 * @package 	Joomla
 * @subpackage 	UnitTest
 * @version 	$Id$
 */

// Call TestOfJFrameworkConfig::main() if this source file is executed directly.
if (!defined('JUNITTEST_MAIN_METHOD')) {
    define('JUNITTEST_MAIN_METHOD', 'TestOfJFrameworkConfig::main');
    $JUNITTEST_ROOT = substr(__FILE__, 0, strpos(__FILE__, DIRECTORY_SEPARATOR.'unittest'));
	require_once($JUNITTEST_ROOT.'/unittest/prepend.php');
}

/**
 * Test class for JFrameworkConfig.
 * Generated by PHPUnit_Util_Skeleton on 2007-02-21 at 23:19:20.
 */
class TestOfJFrameworkConfig extends UnitTestCase {

	/**
	 * Runs the test methods of this class.
	 *
	 * @access public
	 * @static
	 */
	function main() {
		$self = new TestOfJFrameworkConfig;
		$self->run( UnitTestHelper::getReporter() );
	}

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    function tearDown() {
    }


}

// Call TestOfJFrameworkConfig::main() if this source file is executed directly.
if (JUNITTEST_MAIN_METHOD == "TestOfJFrameworkConfig::main") {
    TestOfJFrameworkConfig::main();
}
