INSERT INTO  `#__project_tasks` (
`id` ,
`parent_id` ,
`project_id` ,
`catid` ,
`type` ,
`title` ,
`alias` ,
`description` ,
`estimate` ,
`start_at` ,
`finish_at` ,
`finished` ,
`finished_by` ,
`ordering` ,
`hits` ,
`created` ,
`created_by` ,
`created_by_alias` ,
`modified` ,
`modified_by` ,
`state` ,
`language` ,
`featured` ,
`xreference` ,
`access` ,
`params` ,
`checked_out` ,
`checked_out_time` ,
`rgt` ,
`lft` ,
`level`
)
VALUES (
NULL ,  '0',  '0',  '0',  '0',  '',  '',  '',  '',  '',  '', NULL , NULL ,  '',  '0',  '',  '',  '',  '',  '',  '1',  '',  '',  '',  '',  '',  '0',  '',  '0',  '0',  '0'
);