<?php
require_once 'PHPUnit/Framework.php';

require_once JPATH_BASE. DS . 'libraries' . DS . 'joomla' . DS . 'html' . DS . 'parameter' . DS . 'element' . DS . 'assetgroups.php';

/**
 * Test class for JElementAssetGroups.
 * Generated by PHPUnit on 2009-10-27 at 16:18:00.
 */
class JElementAssetGroupsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JElementAssetGroups
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JElementAssetGroups;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	/**
	 * @todo Decide how to Implement.
	 */
	public function testDummy() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
?>
